"""agregar id_hogar

Revision ID: 7015c57e378d
Revises: 
Create Date: 2026-08-20 17:13:20.745311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7015c57e378d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hogares',sa.Column('id_hogar', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'hogares', ['id_hogar'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'hogares', type_='unique')
    op.drop_column('hogares', 'id_hogar')
    # ### end Alembic commands ###
