"""actualizar tabla lista espera

Revision ID: fa56d0e4667c
Revises: 7015c57e378d
Create Date: 2026-08-25 12:30:27.794078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'fa56d0e4667c'
down_revision: Union[str, Sequence[str], None] = '7015c57e378d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('hogares', 'id_hogar',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.add_column('lista_espera', sa.Column('id_hogar', sa.Integer(), nullable=True))
    op.add_column('lista_espera', sa.Column('cuidador_principal', sa.String(length=150), nullable=False))
    op.add_column('lista_espera', sa.Column('psdf', sa.String(length=150), nullable=False))
    op.add_column('lista_espera', sa.Column('direccion', sa.String(length=250), nullable=False))
    op.add_column('lista_espera', sa.Column('unidad_vecinal', sa.String(length=100), nullable=True))
    op.add_column('lista_espera', sa.Column('telefono', sa.String(length=50), nullable=True))
    op.add_column('lista_espera', sa.Column('profesional_nombre', sa.String(length=150), nullable=True))
    op.add_column('lista_espera', sa.Column('dia', sa.String(length=20), nullable=True))
    op.alter_column('lista_espera', 'hogar_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('lista_espera', 'fecha_solicitud',
               existing_type=sa.DATE(),
               nullable=True)
    op.create_index(op.f('ix_lista_espera_id'), 'lista_espera', ['id'], unique=False)
    op.drop_column('lista_espera', 'dia_preferente')
    op.drop_column('lista_espera', 'disciplina_requerida')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lista_espera', sa.Column('disciplina_requerida', mysql.VARCHAR(length=100), nullable=False))
    op.add_column('lista_espera', sa.Column('dia_preferente', mysql.VARCHAR(length=20), nullable=True))
    op.drop_index(op.f('ix_lista_espera_id'), table_name='lista_espera')
    op.alter_column('lista_espera', 'fecha_solicitud',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('lista_espera', 'hogar_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.drop_column('lista_espera', 'dia')
    op.drop_column('lista_espera', 'profesional_nombre')
    op.drop_column('lista_espera', 'telefono')
    op.drop_column('lista_espera', 'unidad_vecinal')
    op.drop_column('lista_espera', 'direccion')
    op.drop_column('lista_espera', 'psdf')
    op.drop_column('lista_espera', 'cuidador_principal')
    op.drop_column('lista_espera', 'id_hogar')
    op.alter_column('hogares', 'id_hogar',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    # ### end Alembic commands ###
